# Generated by Django 3.0.8 on 2021-09-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_categories', to='tracking.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='cycles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cycles', to='tracking.Cycle'),
        ),
        migrations.AddField(
            model_name='user',
            name='trackables',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_trackables', to='tracking.Trackable'),
        ),
    ]
