# Generated by Django 3.2 on 2021-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(default='https://media.discordapp.net/attachments/709534905733873775/863456819291488296/duck-2-128_1.png'),
        ),
    ]
