# Generated by Django 3.2 on 2021-09-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('users', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='user_categories', to='tracking.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='cycles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cycles', to='tracking.cycle'),
        ),
        migrations.AddField(
            model_name='user',
            name='trackables',
            field=models.ManyToManyField(null=True, related_name='user_trackables', to='tracking.Trackable'),
        ),
    ]
